# Generated by Django 4.1.2 on 2023-06-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mission_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="salary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
