# Generated by Django 4.1.2 on 2023-06-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mission_app", "0002_mission_salary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="category",
            field=models.CharField(
                choices=[
                    ("Movinga", "Movinga"),
                    ("Cocolis", "Cocolis"),
                    ("Categorie1", "Categorie1"),
                    ("Categorie2", "Categorie2"),
                    ("Categorie3", "Categorie3"),
                    ("Extrat", "Extrat"),
                    ("Fret", "Fret"),
                    ("Particulier", "Particulier"),
                    ("Odd", "Odd"),
                ],
                max_length=255,
            ),
        ),
    ]
