# Generated by Django 4.1.2 on 2023-06-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mission_app", "0003_alter_mission_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mission",
            name="end_location",
        ),
        migrations.RemoveField(
            model_name="mission",
            name="start_location",
        ),
        migrations.AddField(
            model_name="mission",
            name="end_zipcode",
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name="mission",
            name="start_zipcode",
            field=models.CharField(default=0, max_length=10),
        ),
    ]
