# Generated by Django 4.1.2 on 2023-06-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mission_app", "0004_remove_mission_end_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="end_zipcode",
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name="mission",
            name="start_zipcode",
            field=models.CharField(default=0, max_length=5),
        ),
    ]
