# Generated by Django 4.1.2 on 2023-06-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mission_app", "0005_alter_mission_end_zipcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="mission_files/"),
        ),
    ]
