# Generated by Django 4.1.2 on 2023-06-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mission_app", "0007_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file",
            field=models.FileField(default="", upload_to="mission_files/"),
        ),
    ]
