# Generated by Django 4.2.2 on 2023-06-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mission_app", "0008_file_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="phone_number",
            field=models.CharField(default=0, max_length=10),
        ),
    ]
