# Generated by Django 4.2.2 on 2023-06-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mission_app", "0009_employee_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField()),
            ],
        ),
    ]
