# Generated by Django 4.2.2 on 2023-06-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mission_app", "0010_stockitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carton",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="mission",
            name="bubble_wrap",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mission",
            name="straps",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mission",
            name="cartons",
            field=models.ManyToManyField(to="mission_app.carton"),
        ),
    ]
