# Generated by Django 4.2.2 on 2023-06-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mission_app", "0012_missionitem_remove_mission_bubble_wrap_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockitem",
            name="type",
            field=models.CharField(default="", max_length=100),
        ),
    ]
