# Generated by Django 4.2.2 on 2023-06-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mission_app", "0013_alter_stockitem_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockitem",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
