# Generated by Django 4.2.2 on 2023-06-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mission_app", "0014_alter_stockitem_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missionitem",
            name="quantity_used",
            field=models.PositiveIntegerField(),
        ),
    ]
