# Generated by Django 4.2.2 on 2023-06-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mission_app", "0016_alter_missionitem_quantity_used"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockitem",
            name="quantity",
        ),
        migrations.AddField(
            model_name="stockitem",
            name="initial_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
