# Generated by Django 4.2.2 on 2023-06-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mission_app", "0017_remove_stockitem_quantity_stockitem_initial_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitem",
            name="quantity_used",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="missionitem",
            name="quantity_used",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
