# Generated by Django 4.2.2 on 2023-06-19 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mission_app", "0018_stockitem_quantity_used_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="missionitem",
            old_name="quantity_used",
            new_name="quantity",
        ),
        migrations.RemoveField(
            model_name="stockitem",
            name="initial_quantity",
        ),
        migrations.RemoveField(
            model_name="stockitem",
            name="quantity_used",
        ),
        migrations.AddField(
            model_name="stockitem",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="missionitem",
            name="mission",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="mission_app.mission",
            ),
        ),
        migrations.AlterField(
            model_name="missionitem",
            name="stock_item",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="mission_app.stockitem",
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="type",
            field=models.CharField(max_length=100),
        ),
    ]
