# Generated by Django 4.2.2 on 2023-06-19 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mission_app", "0021_alter_missionitem_quantity"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MissionItem",
            new_name="MissionStockItem",
        ),
    ]
