# Generated by Django 4.2.2 on 2023-06-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mission_app", "0022_rename_missionitem_missionstockitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField()),
                ("type", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="mission",
            name="items",
        ),
        migrations.DeleteModel(
            name="MissionStockItem",
        ),
        migrations.DeleteModel(
            name="StockItem",
        ),
    ]
