# Generated by Django 4.2.2 on 2023-06-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "mission_app",
            "0023_stock_remove_mission_items_delete_missionstockitem_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="stock",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="stock",
            name="type",
            field=models.CharField(default="", max_length=100),
        ),
    ]
