# Generated by Django 4.2.2 on 2023-06-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mission_app", "0024_alter_stock_name_alter_stock_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="type",
        ),
        migrations.AddField(
            model_name="mission",
            name="stock_items",
            field=models.ManyToManyField(to="mission_app.stock"),
        ),
    ]
