# Generated by Django 4.2.2 on 2023-06-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mission_app", "0027_remove_mission_stock_items_mission_items"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MissionItem",
            new_name="MissionStockItem",
        ),
        migrations.RenameModel(
            old_name="Stock",
            new_name="StockItem",
        ),
        migrations.RenameField(
            model_name="missionstockitem",
            old_name="stock",
            new_name="stock_item",
        ),
        migrations.RemoveField(
            model_name="mission",
            name="items",
        ),
        migrations.AddField(
            model_name="mission",
            name="stock_items",
            field=models.ManyToManyField(
                through="mission_app.MissionStockItem", to="mission_app.stockitem"
            ),
        ),
    ]
